### ISSUE TITLE
REPL prints even when there's a semicolon

### ISSUE THREAD

**Issue by ranjanan** [JuliaComputing/JuliaDT#12]
The Julia REPL in Eclipse DT prints even though there's a semicolon
```
julia>a = 1;
1
julia>b = 2;
2
```

**Comment by snefru** [comment]
May be a side effect of relying on` include_string`, _investigating_ ...

![screen shot 2016-04-04 at 15 52 49](https://cloud.githubusercontent.com/assets/1975882/14251994/56d4d0f4-fa7d-11e5-8cfe-e740f05a66d6.png)
