### ISSUE TITLE
The REPL path

### ISSUE THREAD

**Issue by ranjanan** [JuliaComputing/JuliaDT#14]
When I run the Julia script using the "REPL Julia Script" option, the REPL I get does not open up in the same path as the Julia script I'm running. This means that 
```julia
include("file.jl")
```
gives me a `LoadError` saying the file doesn't exist. Intuitively, one might think that the REPL should recognize the file that you've run as a Julia REPL script in the first place.

**Comment by aviks** [comment]
I'm not sure this can, or should, be fixed. 'REPL Julia Script' should actually load the file in the current open REPL. (It currently opens a new REPL, but I want that to change). In which case, the current path of the file cannot be significant to the running REPL.

**Comment by snefru** [comment]
I'll look into updating the code to take the current workspace directory into account. Incremental evaluation with the console being reused for code snippets can be done as a separate exercise.
