### ISSUE TITLE
Workspace error

### ISSUE THREAD

**Issue by abhijithch** [JuliaComputing/JuliaDT#16]
![workspace](https://cloud.githubusercontent.com/assets/2932535/13941966/28e766da-f013-11e5-981a-537e8c23a10c.jpg)

Doing a workspace() resulted in the above error, this however does'nt occur always. On the second attempt, julia just hangs infintely.

**Comment by aviks** [comment]
This is probably #11

**Comment by abhijithch** [comment]
@aviks The first part is same as #11, but if we hit workspace again julia just hangs infinitely.
