### ISSUE TITLE
Newline missing

### ISSUE THREAD

**Issue by abhijithch** [JuliaComputing/JuliaDT#17]
When we run an empty julia script as REPL script, we get 2 julia prompts in the same line. This is not a showstopper. 
![empty](https://cloud.githubusercontent.com/assets/2932535/13942077/78f9595c-f014-11e5-8293-36d75194cee6.jpg)

**Comment by aviks** [comment]
I think this is fixed by https://github.com/JuliaComputing/JuliaDT/commit/75b662fd70e8e1da0f18bb30ea26f7a4480b4bf8
