### ISSUE TITLE
Plot using Gadfly not showing up

### ISSUE THREAD

**Issue by abhijithch** [JuliaComputing/JuliaDT#18]
<img width="992" alt="plot" src="https://cloud.githubusercontent.com/assets/2932535/13983899/bccf6cd4-f118-11e5-8541-26cefb097c3a.png">

On windows 7 VM, the plot is not showing up after calling the plot function from the REPL.

**Comment by mdpradeep** [comment]
@snefru, We verified this on @AndyGreenwell's Windows 7 system. The behaviour was the same - the plots did not show up. I checked on Windows8.1 and Harsha checked on Windows 10. It works fine. The issue is specific to Windows 7.

**Comment by snefru** [comment]
@mdpradeep, Which version of IE is installed on the machine?

**Comment by AndyGreenwell** [comment]
IE 8

This test was performed using the default version of IE that is present when installing a new copy of Windows 7 SP1 Ultimate using the current ISO file available from MSDN.  The VM also has the most recent version of Google Chrome installed, and Chrome was set as the default browser.

**Comment by abhijithch** [comment]
With IE 9 installed on Windows 7 results in the issue.

**Comment by snefru** [comment]
Thanks for the feedback...

JuliaDT relies on the [SWT Browser component ](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fswt%2Fbrowser%2FBrowser.html) and the underlying browser for plot rendering. Gadfly plots are expressed using SVG. The default browser for Windows 7 is IE8 which has not support for SVG [(Note  Windows Internet Explorer 8 does not natively support SVG and thus requires a plug-in to render SVG.)](https://msdn.microsoft.com/en-us/library/gg589526(v=vs.85).aspx)

IE 9 does support [SVG](http://caniuse.com/#feat=svg) - in principle.

Investigating ...

**Comment by abhijithch** [comment]
After upgrading to IE11 the plot works on Windows 7.

**Comment by snefru** [comment]
Thanks for the update ...

Gadfly plots show-up on the latest test with IE9 (configuration details below).
[(_screenshots across browser also show Gadfly plot appearing as expected_)](https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/#http://htmlpreview.github.io/?https://raw.githubusercontent.com/JuliaComputing/JuliaDT/master/plugins/com.juliacomputing.jldt.eclipse.ui.console/script/sample.html)
![gadfly-svg-ie9-windows7-x86](https://cloud.githubusercontent.com/assets/1975882/14140297/0ffd3934-f670-11e5-8ab1-8ae2fca65bd6.PNG)

### Configuration
1. JuliaDT (x86)
2. Julia version 0.4.5
3. [Windows 7] (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/) 
4. IE9

![system](https://cloud.githubusercontent.com/assets/1975882/14140496/2a3795c8-f671-11e5-8138-9200edfbe988.PNG)

![ie9-spec](https://cloud.githubusercontent.com/assets/1975882/14140533/5ed496fa-f671-11e5-95b5-a322c3a0c563.PNG)

**Comment by abhijithch** [comment]
The configurations I ran the plots, 

1. JuliaDT(X64)
2. Julia version 0.4.3
3. Windows 7 SP1
4. IE9

So the only difference is with the Julia version.

**Comment by snefru** [comment]
@abhijithch can you please test against 3c4f6a61057f08e704eadd0125e6ea732a647a44
[_(uses IE9 standards mode)_](https://msdn.microsoft.com/en-us/library/jj676915%28v=vs.85%29.aspx)

**Comment by abhijithch** [comment]
Thanks @snefru, with the latest commit the plot is working.

**Comment by snefru** [comment]
@abhijithch thanks for your help :)
