### ISSUE TITLE
Julia Plot window does not open up automatically when a plot call is made

### ISSUE THREAD

**Issue by mdpradeep** [JuliaComputing/JuliaDT#19]
When the user creates a plat, the Plot View window does not automatically open. It would be good to open the same if it is not already open.

e.g.
```
julia > using Gadfly
julia > plot(x=rand(10), y=rand(10))
```

It would be good if the above opens the Julia Plot View automatically.

**Comment by bmharsha** [comment]
The plot is not opening up automatically on Windows, I cross checked this on multiple machines, I'm listing the configurations of machines I checked

### Configuration 1
* Windows 2008 R2 Server SP1 (64 bit)
* Internet Explorer 11
* JDK 1.7

### Configuration 2
* Windows 7 (64 bit)
* Internet Explorer 11
* JDK 1.7
