### ISSUE TITLE
PyPlot Support

### ISSUE THREAD

**Issue by snefru** [JuliaComputing/JuliaDT#20]
From #6 
"... looking forward to see plotting from PyPlot, the preferred plotting package for people with Matlab and Python/Matplotlib experience."

**Comment by aviks** [comment]
Should be able to use the `writemime` mechanism for this as well, AFAIK.

**Comment by snefru** [comment]
in progress (219d710741bd624593e93d11fc0d5eae397143b9) ...
![screen shot 2016-04-03 at 18 07 37](https://cloud.githubusercontent.com/assets/1975882/14234027/330ec948-f9d0-11e5-9ee6-4a9a7ffebe3b.png)
