### ISSUE TITLE
Printing help via "?" in Eclipse REPL

### ISSUE THREAD

**Issue by scidom** [JuliaComputing/JuliaDT#21]
It would be nice to be able to read basic documentation in the Eclipse REPL via "?".

**Comment by aviks** [comment]
Yes, this should be easy to do. 

https://github.com/JuliaLang/IJulia.jl/blob/master/src/execute_request.jl#L171-L174

**Comment by snefru** [comment]
Added (be13008a042664ae4495ed627ff43ca62b38652) - thanks @aviks

**Comment by scidom** [comment]
I got the chance today to recompile the dev version, yes, help works now, thank you very much!
