### ISSUE TITLE
Short documentation how to setup the interpreter

### ISSUE THREAD

**Issue by zerocewl** [JuliaComputing/JuliaDT#23]
Please add some lines to your page how to setup the interpreter after installing the plugin, e.g.:

1) Open Menubar: Window -> Preferences -> Julia -> Interpreters
2) Browse to your Julia exec. (e.g. for windows C:\Users\<yourUserName>\AppData\Local\Julia-0.4.5\bin\julia.exe) 
3) Push the add button and navigate to your interpreter system libraries (e.g. for windows  C:\Users\<yourUserName>\AppData\Local\Julia-0.4.5\share\julia\base)

maybe add a screenshot like this one 

![interpreter-dialog](https://cloud.githubusercontent.com/assets/9155214/14703615/004a6b54-07b1-11e6-9053-e9426be2a8a7.png)

[ http://juliacomputing.com/assets/img/interpreter-dialog.png ](url)
from http://juliacomputing.com/blog/2016/02/06/Eclipse-JuliaDT.html

**Comment by ViralBShah** [comment]
Would be great to add this to the README, or perhaps an installation file.

**Comment by snefru** [comment]
More detailed [installation instructions](https://github.com/JuliaComputing/JuliaDT/wiki/Installation) added to the wiki.
