### ISSUE TITLE
Debugging  engine not selected

### ISSUE THREAD

**Issue by olegmikul** [JuliaComputing/JuliaDT#3]
Eclipse with JDT starts fine. Highlighting is fine. Run is ok - it is running, but I can't see outputs in a console. However, I can't start debugging: it shows "Debugging engines not installed or not selected." "Debugging engine not selected". How to select debugging engine?

**Comment by olegmikul** [comment]
Updates: In running mode the console shows outputs if uses 'println' command. So it is ok. 
I have upgraded maven to the latest version and made fresh re-compiling. Still the same error with debugging engine.

**Comment by snefru** [comment]
Thanks for the feedback.

The Debugger is one of the major features on the roadmap and will be available soon although not in the next few weeks. The current deployment is an alpha release. We're in the process of organising the repository and we will be publishing updates on plans, progress and proposals.

Hope this answers your question, please keep us posted on any issues.

**Comment by olegmikul** [comment]
Thank you, understood. 

Looking forward for next releases.

**Comment by ViralBShah** [comment]
Also depends on the Julia debugger getting ready, which is expected in the next julia release.

**Comment by olegmikul** [comment]
Next release - you mean 0.4.x or 0.5 ? 

Meanwhile I am using current eclipse JDT alpha in editor / console mode and it already has some value to work in that environment.

**Comment by ViralBShah** [comment]
It will be 0.5. We do expect to have repl integration though, for interactive use.
