### ISSUE TITLE
JuliaDT incompatible with "Eclipse for Parallel Application Developers" 

### ISSUE THREAD

**Issue by NilsePeter** [JuliaComputing/JuliaDT#31]
Hi,
I can not install the juliaDT to my current eclipse setup using Eclipse for C/C++ for parallel computing in OpenSuse.

The error massage is:

Cannot complete the install because of a conflicting dependency.
  Software being installed: Julia Development Tools 0.0.1.201602080102 (com.juliacomputing.jldt.eclipse.feature.group 0.0.1.201602080102)
  Software currently installed: Eclipse for Parallel Application Developers 4.4.2.20150219-0708 (epp.package.parallel 4.4.2.20150219-0708)
  Only one of the following can be installed at once: 
    Declarative Services 1.4.200.v20131126-2331 (org.eclipse.equinox.ds 1.4.200.v20131126-2331)
    Declarative Services 1.4.300.v20150423-1356 (org.eclipse.equinox.ds 1.4.300.v20150423-1356)
  Cannot satisfy dependency:
    From: Julia Development Tools 0.0.1.201602080102 (com.juliacomputing.jldt.eclipse.feature.group 0.0.1.201602080102)
    To: org.eclipse.equinox.ds [1.4.300.v20150423-1356]
  Cannot satisfy dependency:
    From: Eclipse for Parallel Application Developers 4.4.2.20150219-0708 (epp.package.parallel 4.4.2.20150219-0708)
    To: org.eclipse.epp.package.parallel.feature.feature.group [4.4.2.20150219-0708]
  Cannot satisfy dependency:
    From: Eclipse e4 Rich Client Platform 1.3.101.v20150204-1353 (org.eclipse.e4.rcp.feature.group 1.3.101.v20150204-1353)
    To: org.eclipse.equinox.ds [1.4.200.v20131126-2331]
  Cannot satisfy dependency:
    From: EPP Parallel Feature 4.4.2.20150219-0708 (org.eclipse.epp.package.parallel.feature.feature.group 4.4.2.20150219-0708)
    To: org.eclipse.platform.feature.group [4.4.2.v20150204-1700]
  Cannot satisfy dependency:
    From: Eclipse Platform 4.4.2.v20150204-1700 (org.eclipse.platform.feature.group 4.4.2.v20150204-1700)
    To: org.eclipse.rcp.feature.group [4.4.2.v20150204-1700]
  Cannot satisfy dependency:
    From: Eclipse RCP 4.4.2.v20150204-1700 (org.eclipse.rcp.feature.group 4.4.2.v20150204-1700)
    To: org.eclipse.e4.rcp.feature.group [1.3.101.v20150204-1353]

**Comment by ViralBShah** [comment]
Dup of #33
