### ISSUE TITLE
Cannot complete the install because of a conflicting dependency.

### ISSUE THREAD

**Issue by konstantinmamontov** [JuliaComputing/JuliaDT#33]
Hi,
Cannot complete the install because of a conflicting dependency.

The error message is:
  Software being installed: Julia Development Tools 0.0.1.201602080102 (com.juliacomputing.jldt.eclipse.feature.group 0.0.1.201602080102)
  Software currently installed: Eclipse RCP 4.6.0.v20160606-1342 (org.eclipse.rcp.feature.group 4.6.0.v20160606-1342)
  Only one of the following can be installed at once: 
    Declarative Services 1.4.300.v20150423-1356 (org.eclipse.equinox.ds 1.4.300.v20150423-1356)
    Declarative Services 1.4.400.v20160226-2036 (org.eclipse.equinox.ds 1.4.400.v20160226-2036)
  Cannot satisfy dependency:
    From: Julia Development Tools 0.0.1.201602080102 (com.juliacomputing.jldt.eclipse.feature.group 0.0.1.201602080102)
    To: org.eclipse.equinox.ds [1.4.300.v20150423-1356]
  Cannot satisfy dependency:
    From: Eclipse 4 Rich Client Platform 1.5.0.v20160606-1342 (org.eclipse.e4.rcp.feature.group 1.5.0.v20160606-1342)
    To: org.eclipse.equinox.ds [1.4.400.v20160226-2036]
  Cannot satisfy dependency:
    From: Eclipse RCP 4.6.0.v20160606-1342 (org.eclipse.rcp.feature.group 4.6.0.v20160606-1342)
    To: org.eclipse.e4.rcp.feature.group [1.5.0.v20160606-1342]

**Comment by ViralBShah** [comment]
@mdpradeep Can you help here?

**Comment by fipelle** [comment]
I had the same issue with JuliaDT 0.0.2. I just solved it installing Eclipse Mars (4.5).

**Comment by fredRos** [comment]
I face the same issue appearing with eclipse neon and the "parallel tools platform" suite. Even though #31 was mentioned, I think the question is: will someone make JuliaDT compatible with the latest eclipse release?

**Comment by ViralBShah** [comment]
I believe @snefru fixed this in the latest release. Could you try it out:

https://github.com/JuliaComputing/JuliaDT/releases/tag/v0.0.3

**Comment by ViralBShah** [comment]
Closed by d98a7bf633e1a4beadc344d77046042963f4b633. Reopen if necessary.
