### ISSUE TITLE
Make available in Eclipse Marketplace

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/JuliaDT#34]
I recently gave a talk at the EclipseCon in Bangalore and mentioned this plugin. One suggestion I received was that it will be easy to use this plugin if it were part of the Eclipse marketplace. Is this easy to do?

**Comment by snefru** [comment]
I've added the latest version of the plugin to the [Eclipse Market Place](https://marketplace.eclipse.org/content/juliadt). I'll update the installation instructions next.
