### ISSUE TITLE
is this project dead or alive?

### ISSUE THREAD

**Issue by qlahcim** [JuliaComputing/JuliaDT#35]
I just want to know: Is this project dead or alive? Last commit a years ago?!

**Comment by ViralBShah** [comment]
It is not actively maintained by its original authors.

**Comment by qlahcim** [comment]
So, this mean ... Dead? Because there are no additional developers at all.
I am asking, because Juno IDE is not so good as I expect (unstable, slow, ...)

**Comment by ViralBShah** [comment]
The Juno IDE is maintained - and if you can file issues there, we will get around to those.

**Comment by ViralBShah** [comment]
The other thing a lot of people like is VS Code, and there is decent Julia support for it too.
