### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by FabrizioLacalandra** [JuliaComputing/JuliaDT#5]
Hi,
i never used Eclipse before, but i have installed one version of Mars release and tried to install julia plugin. My problem is that:
1) i did not understand which sw zip i have to download: either the one pointed by
https://github.com/JuliaComputing/JuliaDT/files/121014/com.juliacomputing.jldt.eclipse.repository-0.0.1-SNAPSHOT.zip OR https://github.com/JuliaComputing/JuliaDT/archive/v0.0.1.zip
2) however in both cases once unzipped and going in to install new sw..etc with
-) the first zip there is no JuliaDT directory
-) the second does have a C:\Users\MILP\Desktop\JuliaDT-0.0.1 dir (and several sub dir) but once pointed , Eclipse says "there are no categorized items", and does not let me proceed with next

What am i missing...PS i have also (sucesfully) installed DLTK from here
http://www.eclipse.org/dltk/install.php

Thanks for your help
Fabrizio

**Comment by snefru** [comment]
Hi Fabrizio,

Thanks for the feedback. 
[JuliaDT plugin](https://github.com/JuliaComputing/JuliaDT/files/121014/com.juliacomputing.jldt.eclipse.repository-0.0.1-SNAPSHOT.zip) is the right link for the download. Screenshots of the *zip file* contents and the *Install New Software Dialog* below (also added to [Release notes](https://github.com/JuliaComputing/JuliaDT/releases/tag/v0.0.1))

Hope this helps, please let us know if you have any issues/feedback.

**zip contents**
![screen shot 2016-02-12 at 11 45 22](https://cloud.githubusercontent.com/assets/1975882/13006057/2471c0ae-d17e-11e5-8317-3573f4397445.png)

**Install new software, dialog...**
![screen shot 2016-02-12 at 11 48 29](https://cloud.githubusercontent.com/assets/1975882/13006229/50ccce68-d17f-11e5-9c95-f94117406e09.png)

**Comment by FabrizioLacalandra** [comment]
Hi thanks! Now it seems to work, but only because i manually put the contents of the .zip into a directory named exactly as the .zip (say com.juliacomputing.jldt.eclipse.repository-0.0.1-SNAPSHOT). I suggest to create the zip of the whole dir..

Thanks again

Fabrizio

**Comment by genwei007** [comment]
Hi,
Here is a very naive question. I never use eclipse before. My system is Windows 8.1 64bit.  After opening the eclipseinstaller, what should I do next?
![2016-02-17_211133](https://cloud.githubusercontent.com/assets/6006832/13110440/099f62c2-d5bb-11e5-9e5b-62ef3167fc55.png)

**Comment by snefru** [comment]
Hi Fabrizio,

Hope you’re finding the last release useful. This issue doesn’t seem to have made an appearance recently and I haven’t been able to reproduce on OSX. I’m closing it for the time being, if it does recur could you please include OS details.

Thanks

Taimur
