### ISSUE TITLE
Plotting Gadfly on browser from IDE

### ISSUE THREAD

**Issue by ranjanan** [JuliaComputing/JuliaDT#6]
Usually on the REPL,
```julia
using Gadfly
plot(x = rand(10), y = rand(10), Geom.point)
```
opens a browser window with the plot. 

It would be nice to do this in a browser window from the IDE too. Right now, nothing happens.

**Comment by ViralBShah** [comment]
I believe the plan is to get the Gadfly plot in an eclipse window soon. Would be nice to hear if this will work all plotting packages.

**Comment by olegmikul** [comment]
Yes, would be nice. I am looking forward to see plotting from PyPlot, the preferred plotting package for people with Matlab and Python/Matplotlib experience.

**Comment by snefru** [comment]
Resolved (5accf444247c2d4c37dbb4726c971dd250990b9d, 05c8551b548231fa34cd038cca1dd551563fd7f8, 5f5d4e28ecc8c61da111306f23abbda0012f8b3c)

![screen shot 2016-03-28 at 09 18 53](https://cloud.githubusercontent.com/assets/1975882/14074060/1f7cfd50-f4c6-11e5-8be8-91e21b3a3717.png)

Closing this issue and adding another for PyPlot support #20
