### ISSUE TITLE
REPL integration fails on Windows

### ISSUE THREAD

**Issue by bmharsha** [JuliaComputing/JuliaDT#9]
I'm unable to use the Julia REPL in Eclipse, REPL freezes if we try to execute any commands. No error messages are being displayed on the interface (Maybe errors are being logged somewhere?)

![image](https://cloud.githubusercontent.com/assets/5441491/13742606/bb68fea4-ea02-11e5-9604-8f6c3d1a6be6.png)

In above screenshot, I'm trying to execute a simple command ```1+1``` in the REPL but the REPL has frozen. 

Please note, I was able get an output for following code in Eclipse IDE mode, so the issue is not related to Julia and Eclipse integration, this issue occurs only when I try to use the REPL
```
println("Hello World!")
@show 324+23
```

##### Configuration where this error was detected is as follows

* Windows Server 2008 R2, Service Pack 1
* JDK version = 1.7
* Eclipse version =  Mars.2 (4.5.2)
* Julia version = 0.4.3

**Comment by mdpradeep** [comment]
on a mac book, this works ok.

**Comment by aviks** [comment]
@bmharsha can you see if this is any better with the lastest version of the code?

**Comment by bmharsha** [comment]
> can you see if this is any better with the lastest version of the code?

I just checked the latest version, it doesn't fixes the issue, there were no changes in the REPL behaviour.

I checked the latest code on following configuration 

* Windows 10, 64 bit
* Eclipse version = Mars.2 (4.5.2)
* Julia version = 0.4.3
* JDK version = 1.7

**Comment by aviks** [comment]
That is strange... I now see this working fine in Windows Server 2012 after the last commit :(

**Comment by aviks** [comment]
<img width="1201" alt="screen shot 2016-03-16 at 11 42 15" src="https://cloud.githubusercontent.com/assets/378918/13811288/b79abc52-eb6c-11e5-9e3a-a2bfb267e634.png">

**Comment by bmharsha** [comment]
Are there any log files that I can share that might help the debugging process?

**Comment by bmharsha** [comment]
I just cross checked this on a different system, I encountered same behaviour from the REPL (REPL was non-responsive), the new configuration I tried is as follows

* Windows Server 2008 R2, Service Pack 1
* JDK version = 1.8
* Eclipse version = Mars.2 (4.5.2)
* Julia version = 0.4.3

**Comment by aviks** [comment]
there are some logs in your `[workspace]\.log`. Not sure how useful they are, but see if there is anything relevant there. 

Beyond that, it would be useful if you could load the code in Eclipse (import the source into a running eclipse as a maven project) and run from there. That will enable us to get stdout .

**Comment by aviks** [comment]
Also, can you double check that you are on the latest commit: https://github.com/JuliaComputing/JuliaDT/commit/2e02448d68f08115604b49b5b716a1158a348fd4

**Comment by bmharsha** [comment]
> Also, can you double check that you are on the latest commit

We double checked it, we are on the latest commit.

> there are some logs in your [workspace]\.log. 

I just checked my entire workspace, I couldn't find any log files

> Beyond that, it would be useful if you could load the code in Eclipse (import the source into a running eclipse as a maven project) and run from there. That will enable us to get stdout .

I'm checking this now, I'll revert back once I've something useful.

**Comment by bmharsha** [comment]
> Beyond that, it would be useful if you could load the code in Eclipse (import the source into a running eclipse as a maven project) and run from there. That will enable us to get stdout .

We imported the JuliaDT Maven project, we tried building the entire project, for some reason it's not building all the dependencies, we ended up with an Eclipse IDE without JuliaDT plugin pre-installed in it.

We are trying to build on following configuration 

1) OS = Windows 2008 R2 server
2) JDK = 1.7
3) Eclipse version = Mars 2, Release 4.5.2

**Comment by aviks** [comment]
Try building it on the command line. And then create a new run
configuration for 'run as eclipse application' from inside eclipse. Then
run it from there. It might warn about compile issues before running, but
force it.

For the compile issues generally, install the Plug-in development
environment.

**Comment by snefru** [comment]
I've added the setup requirements for Eclipse to the [readme file](https://github.com/JuliaComputing/JuliaDT/blob/master/README.md).

**Comment by bmharsha** [comment]
I followed the instructions and installed all the prerequisites mentioned in the updated readme file, as shown in the screenshot below, I've imported the JuliaDT project and ran this project 

![untitled](https://cloud.githubusercontent.com/assets/5441491/13842944/dd08d916-ec56-11e5-8e4b-00d5711a4ebe.png)

Once we run, a new Eclipse process gets initiated, issue is, we were unable to create a project in this Eclipse, we tried many times, the launched Eclipse becomes unresponsive, as shown in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/5441491/13842524/a408c38a-ec54-11e5-8f0d-bda77ea63651.png)

Following is the exact error message extracted from the console

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [bundleresource://950.fwk1442166269:1/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [bundleresource://950.fwk1442166269:2/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "Thread-9" Exception in thread "Thread-8" Exception in thread "Worker-10" Error while logging event loop exception:
Error while logging event loop exception:
Exception in thread "DLTK indexing" Exception in thread "Worker-8" Exception in thread "Worker-12" Exception in thread "Worker-6" 
```

**Comment by bmharsha** [comment]
Commit https://github.com/JuliaComputing/JuliaDT/commit/35a8c58f90d43a4532e3c97cb6a43a8cc3f59db7 fixes this issue but it breaks the functionality that was working before, Outline doesn't shows function or variable mappings for code under a module.

For example:- Following code doesn't creates any mappings in the Outline
```
module fdfds
  function mult(a)
      a * 100
  end  
  export mult
end
```
Although, Outline does shows up mappings for functions that are written outside the scope of a Module.

Apart from aforementioned issue, we have one more minor issue in the REPL. REPL doesn't flushes out the entire error message at once.
Example:- 
```
julia>this_("should create an error")
LoadError: UndefVarError: this_ not defined
while loading string, in expression starting on line 1

julia>a = "I am a valid statement"
"error"
I am a valid statement

julia>a = "I am still a valid statement"
I am still a valid statement

julia>
```
In the above code snippet, we  encountered an error in the first statement but the second statement was valid and yet it displayed the string ```error```, this happens to every statement that gets executed after an erroneous statement is encountered, you can observe the third statement went fine.

**Comment by aviks** [comment]
Yeah, that "error" thing I know.. need to fix.

**Comment by bmharsha** [comment]
I've filed both the issues that I'd reported in my previous message

* https://github.com/JuliaComputing/JuliaDT/issues/10 = Code within the scope of the module are not being mapped in the Outline
* https://github.com/JuliaComputing/JuliaDT/issues/11 = REPL sometimes displays "error", even though the statement is valid
